name: "playstation-box"
description: "Update a pinned gist to contain PlayStation stats"
branding:
  icon: "flag"
  color: "yellow"
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: uv sync
    - name: Run
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        PYTHONUNBUFFERED: 1
      run: uv run python src/main.py
